### ISSUE TITLE
"Invalid geometry supplied for task."

### ISSUE THREAD

**Issue by matkoniecz** [maproulette/maproulette-backend#337]
I created http://maproulette.org/ui/admin/list/Challenge/1986 based on following query

```
[out:json];
(
node(4395771247);
way(26782224);
); out body geom qt;
```

On selecting view action I see map with two markers (as expected).

I clicked on either of two markers and selected "Fix" button in the map view and only got a quickly flashing message "Invalid geometry supplied for task".

Replicable (hopefully) version of #249

**Comment by mvexel** [comment]
Interesting, thanks for the reproducible case, will investigate.

**Comment by mgcuthbert** [comment]
This should be resolved in the current version.

**Comment by double-a** [comment]
Still reproducible, e.g. using [this project](http://maproulette.org/map/2667)

**Comment by ljdelight** [comment]
Works fine with the latest version, closing this old issue
